use crate::error::Result;
use std::fs;
use std::io::Write;
use std::os::unix::fs::OpenOptionsExt;
use std::process::Command;

const RESOLV_CONF_SYSTEM: &str = "/tmp/resolv.conf.auto";

/// DNS server entry with its source interface.
#[derive(Debug, Clone)]
pub struct DnsEntry {
    pub server: String,
    pub interface: String,
}

/// Manages resolv.conf updates on failover.
///
/// On OpenWrt, dnsmasq reads from /tmp/resolv.conf.auto by default.
/// We write our own version and signal dnsmasq to re-read it.
pub struct DnsManager {
    entries: Vec<DnsEntry>,
}

impl DnsManager {
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
        }
    }

    /// Set the DNS servers for a given interface. Replaces any existing
    /// entries for that interface.
    pub fn set_servers(&mut self, interface: &str, servers: &[String]) {
        self.entries.retain(|e| e.interface != interface);
        for s in servers {
            self.entries.push(DnsEntry {
                server: s.clone(),
                interface: interface.to_string(),
            });
        }
    }

    /// Remove all DNS entries for an interface (called on failover to offline).
    pub fn remove_interface(&mut self, interface: &str) {
        self.entries.retain(|e| e.interface != interface);
    }

    /// Write resolv.conf and signal dnsmasq. Called after any DNS change.
    pub fn apply(&self) -> Result<()> {
        let mut content = String::from("# Generated by nopal -- do not edit\n");
        for entry in &self.entries {
            content.push_str(&format!("nameserver {} # {}\n", entry.server, entry.interface));
        }

        // Atomic write via temp file + rename. Use PID in path and O_EXCL
        // to prevent symlink attacks on the predictable temp location.
        let tmp = format!("{RESOLV_CONF_SYSTEM}.nopal.{}", std::process::id());
        let _ = fs::remove_file(&tmp); // clean up stale file from previous write
        let mut f = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o644)
            .open(&tmp)?;
        f.write_all(content.as_bytes())?;
        f.sync_all()?;
        fs::rename(&tmp, RESOLV_CONF_SYSTEM)?;

        // Signal dnsmasq to re-read resolv.conf
        let _ = Command::new("killall")
            .args(["-HUP", "dnsmasq"])
            .output();

        log::info!("updated DNS with {} servers", self.entries.len());
        Ok(())
    }

    /// Returns the current list of active DNS servers.
    #[allow(dead_code)]
    pub fn active_servers(&self) -> &[DnsEntry] {
        &self.entries
    }
}
