## DNS manager: writes interface DNS servers to resolv.conf.
##
## Maintains per-interface DNS server lists and writes them atomically
## to /tmp/resolv.conf.auto. Signals dnsmasq via SIGHUP to pick up changes.

import std/[posix, os, logging, strutils, strformat]

const
  ResolvConfPath = "/tmp/resolv.conf.auto"
  DnsmasqPidPath = "/var/run/dnsmasq/dnsmasq.pid"

type
  DnsEntry = object
    server: string
    interfaceName: string

  DnsManager* = object
    entries: seq[DnsEntry]

proc initDnsManager*(): DnsManager =
  DnsManager(entries: @[])

proc removeInterface*(dm: var DnsManager, iface: string) =
  ## Remove all DNS servers for an interface.
  var i = 0
  while i < dm.entries.len:
    if dm.entries[i].interfaceName == iface:
      dm.entries.delete(i)
    else:
      inc i

proc setServers*(dm: var DnsManager, iface: string, servers: openArray[string]) =
  ## Set DNS servers for an interface. Replaces any previous servers.
  dm.removeInterface(iface)
  # Sanitize interface name for defense-in-depth (written to resolv.conf comment)
  let cleanIface = iface.strip()
  if '\n' in cleanIface or '\r' in cleanIface:
    return
  for s in servers:
    let clean = s.strip()
    if clean.len > 0 and '\n' notin clean and '\r' notin clean:
      dm.entries.add(DnsEntry(server: clean, interfaceName: cleanIface))

func activeServers*(dm: DnsManager): seq[tuple[server, iface: string]] {.raises: [].} =
  ## Return all active DNS servers with their interface names.
  for e in dm.entries:
    result.add((server: e.server, iface: e.interfaceName))

proc apply*(dm: DnsManager) =
  ## Write DNS servers to resolv.conf atomically and signal dnsmasq.
  var content = "# Generated by nopal -- do not edit\n"
  for e in dm.entries:
    content.add(fmt"nameserver {e.server} # {e.interfaceName}" & "\n")

  # Atomic write: open with O_EXCL (fail if exists), fsync, rename
  let tmpPath = fmt"{ResolvConfPath}.nopal.{getpid()}"

  # Remove stale temp file from previous crash
  try: removeFile(tmpPath)
  except OSError: discard

  let fd = posix.open(cstring(tmpPath),
                      posix.O_WRONLY or posix.O_CREAT or posix.O_EXCL, 0o644)
  if fd < 0:
    warn fmt"failed to create temp DNS file: {strerror(errno)}"
    return

  let written = posix.write(fd, cast[pointer](cstring(content)), content.len)
  if written < 0 or written != content.len:
    warn fmt"failed to write DNS config: {strerror(errno)}"
    discard posix.close(fd)
    try: removeFile(tmpPath)
    except OSError: discard
    return

  # fsync to ensure data is durable before rename
  discard posix.fsync(fd)
  discard posix.close(fd)

  try:
    moveFile(tmpPath, ResolvConfPath)
    info fmt"wrote {dm.entries.len} DNS servers to {ResolvConfPath}"
  except OSError:
    warn fmt"failed to rename DNS config: {getCurrentExceptionMsg()}"
    try: removeFile(tmpPath)
    except OSError: discard
    return

  # Signal dnsmasq to re-read resolv.conf via PID file
  try:
    let pidStr = readFile(DnsmasqPidPath).strip()
    let pid = parseInt(pidStr)
    if pid > 0:
      discard posix.kill(Pid(pid), posix.SIGHUP)
  except:
    debug "dnsmasq not running or PID file not found"

when isMainModule:
  import std/unittest

  suite "DnsManager":
    test "setServers and removeInterface":
      var dm = initDnsManager()
      dm.setServers("wan", ["8.8.8.8", "8.8.4.4"])
      dm.setServers("lte", ["1.1.1.1"])
      check dm.activeServers.len == 3

      dm.removeInterface("wan")
      check dm.activeServers.len == 1
      check dm.activeServers[0].server == "1.1.1.1"
      check dm.activeServers[0].iface == "lte"

    test "setServers replaces previous":
      var dm = initDnsManager()
      dm.setServers("wan", ["8.8.8.8"])
      dm.setServers("wan", ["1.1.1.1", "9.9.9.9"])
      check dm.activeServers.len == 2
      check dm.activeServers[0].server == "1.1.1.1"

    test "removeInterface on empty is no-op":
      var dm = initDnsManager()
      dm.removeInterface("wan")
      check dm.activeServers.len == 0

    test "newlines in server strings are rejected":
      var dm = initDnsManager()
      dm.setServers("wan", ["8.8.8.8\nnameserver 1.2.3.4", "valid.server"])
      # The injected entry should be rejected, only valid.server kept
      check dm.activeServers.len == 1
      check dm.activeServers[0].server == "valid.server"
