## DNS manager: writes interface DNS servers to resolv.conf.
##
## Maintains per-interface DNS server lists and writes them atomically
## to /tmp/resolv.conf.auto. Signals dnsmasq via SIGHUP to pick up changes.

import std/[posix, os, osproc, logging, strutils]

const
  ResolvConfPath = "/tmp/resolv.conf.auto"

type
  DnsEntry = object
    server: string
    interfaceName: string

  DnsManager* = object
    entries: seq[DnsEntry]

proc initDnsManager*(): DnsManager =
  DnsManager(entries: @[])

proc removeInterface*(dm: var DnsManager, iface: string) =
  ## Remove all DNS servers for an interface.
  var i = 0
  while i < dm.entries.len:
    if dm.entries[i].interfaceName == iface:
      dm.entries.delete(i)
    else:
      inc i

proc setServers*(dm: var DnsManager, iface: string, servers: openArray[string]) =
  ## Set DNS servers for an interface. Replaces any previous servers.
  dm.removeInterface(iface)
  for s in servers:
    dm.entries.add(DnsEntry(server: s, interfaceName: iface))

proc activeServers*(dm: DnsManager): seq[tuple[server, iface: string]] =
  ## Return all active DNS servers with their interface names.
  for e in dm.entries:
    result.add((server: e.server, iface: e.interfaceName))

proc apply*(dm: DnsManager) =
  ## Write DNS servers to resolv.conf atomically and signal dnsmasq.
  var content = "# Generated by nopal -- do not edit\n"
  for e in dm.entries:
    content.add("nameserver " & e.server & " # " & e.interfaceName & "\n")

  # Atomic write: temp file + sync + rename
  let tmpPath = ResolvConfPath & ".nopal." & $getpid()
  try:
    writeFile(tmpPath, content)
    moveFile(tmpPath, ResolvConfPath)
    info "wrote " & $dm.entries.len & " DNS servers to " & ResolvConfPath
  except OSError:
    warn "failed to write DNS config: " & getCurrentExceptionMsg()
    try: removeFile(tmpPath)
    except: discard
    return

  # Signal dnsmasq to re-read resolv.conf
  let (_, exitCode) = execCmdEx("killall -HUP dnsmasq 2>/dev/null")
  if exitCode != 0:
    debug "dnsmasq not running or signal failed (expected on some setups)"

when isMainModule:
  import std/unittest

  suite "DnsManager":
    test "setServers and removeInterface":
      var dm = initDnsManager()
      dm.setServers("wan", ["8.8.8.8", "8.8.4.4"])
      dm.setServers("lte", ["1.1.1.1"])
      check dm.activeServers.len == 3

      dm.removeInterface("wan")
      check dm.activeServers.len == 1
      check dm.activeServers[0].server == "1.1.1.1"
      check dm.activeServers[0].iface == "lte"

    test "setServers replaces previous":
      var dm = initDnsManager()
      dm.setServers("wan", ["8.8.8.8"])
      dm.setServers("wan", ["1.1.1.1", "9.9.9.9"])
      check dm.activeServers.len == 2
      check dm.activeServers[0].server == "1.1.1.1"

    test "removeInterface on empty is no-op":
      var dm = initDnsManager()
      dm.removeInterface("wan")
      check dm.activeServers.len == 0
