#!/bin/sh /etc/rc.common

START=19
STOP=90
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/nopald
    procd_set_param respawn 3600 5 5
    procd_set_param file /etc/config/nopal
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    procd_send_signal nopald '*' HUP
}

service_triggers() {
    procd_add_reload_trigger "nopal"
}
